# Generated by Django 3.1.4 on 2020-12-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp1', '0003_destinations_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='hits',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
