# Generated by Django 3.1.4 on 2020-12-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp1', '0004_destinations_hits'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destinations',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
