# Generated by Django 3.1.4 on 2020-12-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp1', '0005_auto_20201209_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('discountPercentage', models.IntegerField(default=0)),
            ],
        ),
    ]
